trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfigurations: 'Release'

steps:
- script: dotner build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'